/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p39.reto4.view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.p39.reto4.controller.ControllerRequerimientos;
import utp.misiontic2022.c2.p39.reto4.model.vo.Requerimiento_1;
import utp.misiontic2022.c2.p39.reto4.model.vo.Requerimiento_2;
import utp.misiontic2022.c2.p39.reto4.model.vo.Requerimiento_3;

/**
 *
 * @author HP
 */
public class JFrameRequerimientos extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRequerimiento
     */
    public JFrameRequerimientos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReq1 = new javax.swing.JButton();
        btnReq2 = new javax.swing.JButton();
        btnReq3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReq = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnReq1.setBackground(new java.awt.Color(0, 153, 153));
        btnReq1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnReq1.setForeground(new java.awt.Color(255, 255, 255));
        btnReq1.setText("Requerimiento1");
        btnReq1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReq1.setFocusPainted(false);
        btnReq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReq1ActionPerformed(evt);
            }
        });

        btnReq2.setBackground(new java.awt.Color(0, 153, 153));
        btnReq2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnReq2.setForeground(new java.awt.Color(255, 255, 255));
        btnReq2.setText("Requerimiento2");
        btnReq2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReq2.setFocusPainted(false);
        btnReq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReq2ActionPerformed(evt);
            }
        });

        btnReq3.setBackground(new java.awt.Color(0, 153, 153));
        btnReq3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnReq3.setForeground(new java.awt.Color(255, 255, 255));
        btnReq3.setText("Requerimiento3");
        btnReq3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReq3.setFocusPainted(false);
        btnReq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReq3ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tableReq.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tableReq.setForeground(new java.awt.Color(0, 0, 0));
        tableReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableReq);

        btnRegresar.setBackground(new java.awt.Color(0, 153, 153));
        btnRegresar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReq2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReq3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReq3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReq1ActionPerformed
        String[] columnNombre = {"Fecha","Id Compra","Nom. Proveedor","Pagado"};
        ControllerRequerimientos controller = new ControllerRequerimientos();
        ArrayList<Requerimiento_1> listaReq1;
        try {
            listaReq1 = controller.consultarRequerimiento1();
            Object[][] datos = new Object[listaReq1.size()][columnNombre.length];
            int index = 0; 
            for(Requerimiento_1 req : listaReq1){
                datos[index][0] = req.getFechaCompra();
                datos[index][1] = req.getCodigoCompra();
                datos[index][2] = req.getNombreProveedor();
                datos[index][3] = req.getValorPagado();
                index += 1;
            }
            DefaultTableModel modelT = new DefaultTableModel(datos,columnNombre);
            tableReq.setModel(modelT);
        } catch (SQLException e) {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_btnReq1ActionPerformed

    private void btnReq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReq2ActionPerformed
        String[] columnNombre = {"Fec. Ini.","Nombre Ciudad","Nom. Constructora","Nombre Lider","Codigo Tipo","Estrato"};
        ControllerRequerimientos controller = new ControllerRequerimientos();
        ArrayList<Requerimiento_2> listaReq2;
        try {
            listaReq2 = controller.consultarRequerimiento2();
            Object[][] datos = new Object[listaReq2.size()][columnNombre.length];
            int index = 0; 
            for(Requerimiento_2 req : listaReq2){
                datos[index][0] = req.getFechaInicio();
                datos[index][1] = req.getNombreCiudad();
                datos[index][2] = req.getNombreConstructora();
                datos[index][3] = req.getNombreLider();
                datos[index][4] = req.getCodigoTipo();
                datos[index][5] = req.getEstrato();
                index += 1;
            }
            DefaultTableModel modelT = new DefaultTableModel(datos,columnNombre);
            tableReq.setModel(modelT);
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnReq2ActionPerformed

    private void btnReq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReq3ActionPerformed
        String[] columnNombre = {"Abrev."};
        ControllerRequerimientos controller = new ControllerRequerimientos();
        ArrayList<Requerimiento_3> listaReq3;
        try {
            listaReq3 = controller.consultarRequerimiento3();
            Object[][] datos = new Object[listaReq3.size()][columnNombre.length];
            int index = 0; 
            for(Requerimiento_3 req : listaReq3){
                datos[index][0] = req.getNombreAbreviado();
                index += 1;
            }
            DefaultTableModel modelT = new DefaultTableModel(datos,columnNombre);
            tableReq.setModel(modelT);
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnReq3ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRequerimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReq1;
    private javax.swing.JButton btnReq2;
    private javax.swing.JButton btnReq3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReq;
    // End of variables declaration//GEN-END:variables
}
